// ⚠️  DEPRECATED — This file is no longer used.
// The correct parser is at: utils/resumeParser.js
// This file is kept only to avoid breaking any accidental old imports.
// Do NOT edit this file. Edit utils/resumeParser.js instead.

module.exports = require('./utils/resumeParser');
