// ⚠️  DEPRECATED — This file is no longer used.
// The correct middleware is at: middleware/uploadMiddleware.js
// Do NOT edit this file. Edit middleware/uploadMiddleware.js instead.

module.exports = require('./middleware/uploadMiddleware');
