// ⚠️  DEPRECATED — This file is no longer used.
// The correct middleware is at: middleware/authMiddleware.js
// Do NOT edit this file. Edit middleware/authMiddleware.js instead.

module.exports = require('./middleware/authMiddleware');
